### ISSUE TITLE
The created ico's size is only 16 * 16

### ISSUE THREAD

**Issue by koibi2** [Si13n7/ImageToIcon#1]
i can't  resize it.
i used it → https://github.com/Si13n7/ImageToIcon/releases

**Comment by Si13n7** [comment]
Your description is very poor... Looks like I need to guess what you did... Then I'm just assuming that you've opened an image with a small pixel size. Is that correct? if not, don't be afraid to correct me!

The problem is that this tool never creates larger images than the original file because the image quality would be crap. If you want larger images, you have to open a large one first. Then you can change every single image by clicking on it. It adapts automatically to the selected size, even too small images are adjusted. But I would'nt recommend using too small images.

So best result you will get if you open an image that is at least 256x256 pixels because it creates all the you are looking for. 😉

**Comment by koibi2** [comment]
it really can't be..
this is my img.it is 360*360.
![1](https://user-images.githubusercontent.com/34370367/56887348-f5596200-6aa3-11e9-89e1-b50eeb92a009.png)

I use your tool open the img .
But when i click the img,it ask me to open img again?
![2](https://user-images.githubusercontent.com/34370367/56887459-4406fc00-6aa4-11e9-84b8-d4946f969e62.png)

I try to save icon.but it just be 8*8 or 16*16.
![3](https://user-images.githubusercontent.com/34370367/56887469-49644680-6aa4-11e9-9f1f-db592542c7aa.png)

I'm in win10、64.

**Comment by Si13n7** [comment]
Thanks for the description! 😉 

Can you upload your JPG source image and the icon you created so that I can check this out?

**Comment by koibi2** [comment]
[my_img_and_ico.zip](https://github.com/Si13n7/ImageToIcon/files/3126960/my_img_and_ico.zip)
Here it is.

**Comment by Si13n7** [comment]
After a few tests, I still could not find any problem.

I can choose a size when I try to open your create `360.ico` file with **Adobe Photoshop**:
![0](https://user-images.githubusercontent.com/6128966/56908080-e8d60900-6aa5-11e9-9ef2-0daae5588d11.jpg)

And **GIMP** also opens all images correctly without problems:
![1](https://user-images.githubusercontent.com/6128966/56908367-76195d80-6aa6-11e9-82b1-ff4eec3586de.PNG)

But then I saw that the **Windows Explorer** displays a size of 8x8,
but the image in the preview clearly has a better quality:
![2](https://user-images.githubusercontent.com/6128966/56910502-022d8400-6aab-11e9-8f3b-fd7aee663592.PNG)

So I checked the file header anyway and quickly created a [tool to extract all images from an icon file](https://github.com/Si13n7/ImagesFromIcon/releases):
![3](https://user-images.githubusercontent.com/6128966/56908976-a4e40380-6aa7-11e9-831f-96b412d8fa44.PNG)
_The files are named with the information from the file header of the icon. The first number is the pixel format, followed by the width and height. Please note that width and height must be stored as an unsigned 8-bit integer whose maximum value is 255. Therefore, images with a large size are defined with 0 (zero) in the file header. So the `32@0x0.png` file in the picture above has a size of 256x256 pixels._

At least the file header was correct and I was able to extract all the images. In the next step, I created an icon directly with **GIMP** to see if there are any differences to my tool. There were no relevant differences and the same problem with the **Windows Explorer**.

Then I created a symbol with an old format to check the differences with the **Windows Explorer**. I noticed that PNG compression icons always show the smallest size and older icons display the largest size. So I assume that this is certainly intended by Microsoft.

---

### The end of a long story:

There are no problems and everything works as intended. But please note that my tool only creates PNG compressed icons. These were used for the first time on Windows Vista. Therefore, it may be possible that not every software can handle them.

But I think if a graphics software can not handle a format that has existed for 13 years, the software is absolutely crap. 😜
